### ISSUE TITLE
Problem with using the function newtonraphson to simulate an article

### ISSUE THREAD

**Issue by hsoftproject** [mikofski/NewtonRaphson#1]
Greetings and Regards
I'm simulating an article with link https://ieeexplore.ieee.org/document/4137586/ that uses the Newton-Raphson method , I need to do Equation 11 equation , And I wrote the equations in the following code :
`clc ;
clear ;
close all;
variable
global h c lambda J dz R_p n_p a1 a2 a3 alpha_1 alpha_2 eta q d ...
    lambda0 n0 g Iav E g_mp S_sp alpha_n L

lambda= 1330*1e-9;  % signal wavelength in m
E=(h*c)/(lambda); % signal energy

alpha_n=@(n)alpha_1+alpha_2*n;
tau = @(n)(((A+(B*n)+((C)*(n.^2)))).^-1);%equation (8) /// درسته
 R_p=@(n)(A*n)+(B*(n.^2))+(C*(n.^3))  ;   %equation (8) from Ref. 14   %
  lambda_p=@(n)lambda-a3*(n-n_p);%equation (3) ///درسته
  
  g_mp=@(n) a1*(n-n0)-(a2*((lambda-lambda_p(n)).^2));%equation (2)
  
   g=@(n)(confin_optional*(g_mp(n)-alpha_n(n)));%equation (4)
   
    G_s=@(n) exp(sum((confin_optional*g_mp(n)-alpha_n(n))*(L*1e-6)));%% single pass gain        equation (7)
     F1=@(n)((beta_0*R_p(n))/(2*((confin_optional*g_mp(n))-alpha_n(n))));
  F2=@(n)((R1+R2).*((G_s(n)-1).^2)+(2.*(1-R1*R2.*G_s(n)).*(G_s(n)-1)));
  F3=@(n) (L*10e-6).*((confin_optional.*g_mp(n))-alpha_n(n)).*(1-(R1.*R2).*(G_s(n).^2));
  S_sp=@(n) F1(n).*((F2(n)./F3(n))-2);
   I_input=db(-10)+db(-8);
     Iav=@(n) (I_input *10^-3 )*((G_s(n)-1)/(g(n)*(L*10e-6)));
J=@(n) ((q*d)/tau(n))*n*100;
%      aa=((eta*J)/(q*d))
% bb=((n)/(tau))
% cc=(g.*Iav)./E
% ggg=g_mp.*(S_sp)

    dn=@(n) ((eta*J(n))/(q*d))-((n)/(tau(n)))-((g(n).*Iav(n))./E)+(g_mp(n).*(S_sp(n)));
    
fun= @(n) [alpha_n(n) ,tau(n) ,R_p(n), lambda_p(n), g_mp(n),g(n),G_s(n),S_sp(n),Iav(n),J(n),dn(n)]  ; `

Then I called the Newton-Raphson function in the following form:
`    options = optimset('MaxIter',6); % set TolX
[n, resnorm, f, exitflag, output, jacob] = newtonraphson(fun, n0, options);`
Ultimately, the goal is to Simulated carrier density along the SOA cavity , But the output appears in the form below, so please help me in this simulation if possible

output: 
`
     Niter    resnorm   stepnorm     lambda      rcond  convergence
-------------------------------------------------------------------
         0  1.566e+34          0          1          0          Inf
Warning: Rank deficient, rank = 0, tol =  0.000000e+00. 
> In newtonraphson (line 139)
In NewtonRsphdonKannely (line 39)`

**Comment by mikofski** [comment]
It's hard to tell, but it may be that either the initial guess are too far from the optimum, or the Jacobian matrix is [singular](https://mathworld.wolfram.com/SingularMatrix.html) (can't evaluate because determinant is zero) or too stiff (both big and small absolute values). If the condition of the matrix is bad, _IE_ there residual sensitivities `dFi / dxj` that are very close to the [machine precision](https://en.wikipedia.org/wiki/Machine_epsilon) of your computer in both the biggest and smallest absolute values it can represent, then there is a very weak coupling between the governing equations and the variables, and they cannot converge. Or it's possible there's a syntax error in your code, perhaps a formula is not entered correctly - this has happened to me so many times 😕 . If you double check your formulas and experiment with many initial guesses, review the condition of the Jacobian, and if it's bad you can try a psuedo-steady-state / quasi-equilibrium solution. If there is one variable with very high residual sensitivities (quickly changing), then pull that variable out, and pretend to solve it for steady state, assuming it's infinitely fast. Then use the steady state value as a constant. Does it solve now? Resolve for the new steady state condition and run again. Repeat until you solve for the infinitely fast variable. Ditto if there is one that is slower than all the others.

Another thing to try is to normalize all variables to their characteristic ranges, and make your governing equations non-dimensional. This usually improves the condition of the Jacobian. Another thing to try is to align all of the non-zero elements along the diagonal and make the residual as sparse as possible.

The last thing you can try is preconditioning or artificial diffusion. In `newtonraphson.m` there's a place to set the weights

https://github.com/mikofski/NewtonRaphson/blob/c50de3469eda884852eb671ec46eca5673b0f8b8/newtonraphson.m#L98-L99

Update this to something that improves the condition of the Jacobian.

Also, I assumed you are not providing the Jacobian. Sometimes providing this, if it's not too expensive can speed up convergence. However, other times it can make the Jacobian singular, and the Secant method is more stable. To force `newtonraphson.m` to use the Secant method, do not provide the Jacobian, and `newtonraphson.m` will approximate it for you.

Sorry, that's the best I can do. I am not maintaining `newtonraphson.m` anymore and I don't use MATLAB. As an alternate, you could try [Python's SciPy Optimize packag](https://docs.scipy.org/doc/scipy/tutorial/optimize.html)e, which has many good non-linear solvers.

**Comment by hsoftproject** [comment]
>

**Comment by hsoftproject** [comment]
tank you for replay
I will try all the things you said and report it in this place
